# -*- coding: utf-8 -*-
"""VentaPerfumes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqFs-7O3jXGrpPOspWEoWrsR_TWWJkp5
"""



# Download latest version
path = kagglehub.dataset_download("kanchana1990/perfume-e-commerce-dataset-2024")

print("Path to dataset files:", path)
